apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceAccountName: monitoring
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.1.6
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-config-volume
          readOnly: false
      volumes:
      - name: grafana-config-volume
        persistentVolumeClaim:
          claimName: grafana-claim
---
